### ISSUE TITLE
Tooltip still says "Press LSHIFT to dismount"

### ISSUE THREAD

**Issue by TheRandomLabs** [Niko-sk2x/UnRideKeybind#1]
When I enter a minecart/boat, the tooltip says "Press LSHIFT to dismount", even though I've changed the bind to Z.

**Comment by Niko-sk2x** [comment]
Because the GUI still shows keybind for sneak...
It's a very minor GUI issue, so it's unlikely I will fix it anytime soon (considering it will involve a bit of nontrivial work)

**Comment by TheRandomLabs** [comment]
Oh well, thanks for checking it out.

**Comment by TheRandomLabs** [comment]
In case anyone is interested, I've implemented a fixed version in [RandomPatches](https://github.com/TheRandomLabs/RandomPatches/commit/e822142414d7adb149ecf1d06f4e8ba38ddb470c).

**Comment by Niko-sk2x** [comment]
Makes sense to be part of something bigger. I only implemented it as a separate mod because I needed it and there was no other mod that did it.
